language: php

php:
   - 5.3
   - 5.4

branches:
  exclude:
    - 1.0.0

env:
   - DB=mysql TYPO3=TYPO3_6-1 INTEGRATION=master
   - DB=mysql TYPO3=TYPO3_6-0 INTEGRATION=master
   - DB=mysql TYPO3=TYPO3_4-5 INTEGRATION=TYPO3_4-7

matrix:
  include:
    - php: 5.5
      env: DB=mysql TYPO3=master INTEGRATION=master

services:
  - memcached

before_script:
# Install build dependencies
  - cd ..
  - git clone --single-branch --recursive --branch $INTEGRATION --depth 1 https://github.com/typo3-ci/TYPO3-Travis-Integration.git build-environment;
  - git clone --single-branch --recursive --branch $TYPO3 --depth 1 https://github.com/TYPO3/TYPO3.CMS.git core;
  - source build-environment/install-helper.sh;
  - if [[ "$TRAVIS_PHP_VERSION" != "5.5" ]]; then installPhpModule igbinary; fi;
  - installPhpModule -y memcache;
  - installPhpModule redis;
  - if [[ "$TRAVIS_PHP_VERSION" == "5.3" ]]; then installPhpModule -y apc; fi;
  - pyrus install pear/PHP_CodeSniffer;
  #- pear install --alldeps phpmd/PHP_PMD;
  - phpenv rehash;

# Install rudimentary TYPO3
  - git clone --single-branch --recursive --branch $TYPO3 --depth 1 git://git.typo3.org/TYPO3v4/Distributions/Introduction.git build-environment/Introduction;
  - mv core/typo3 .;
  - if [[ -d core/t3lib ]]; then mv core/t3lib . ; fi;
  - mv build-environment/typo3conf .;
  - mv build-environment/Introduction/fileadmin/ .;
  - mv build-environment/Introduction/uploads/ .;
  - mv build-environment/Introduction/typo3temp/ .;

# Setup DB
  - if [[ "$DB" == "mysql" ]]; then mysql -e "DROP DATABASE IF EXISTS typo3_test;" -uroot; fi;
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS typo3_test;" -uroot; fi;
  - if [[ "$DB" == "mysql" ]]; then mysql -uroot typo3_test < build-environment/Introduction/typo3conf/ext/introduction/Resources/Private/Subpackages/Introduction/Database/introduction.sql; fi;
  - if [[ "$DB" == "mysql" && -f build-environment/dbimport/cache_tables.sql ]]; then mysql -uroot typo3_test < build-environment/dbimport/cache_tables.sql; fi;
  - if [[ "$DB" == "mysql" && -f  build-environment/dbimport/cli_users.sql ]]; then mysql -uroot typo3_test < build-environment/dbimport/cli_users.sql; fi;
  - echo "INSERT INTO be_users (pid, username, password, TSconfig) VALUES (0,'_cli_lowlevel','5f4dcc3b5aa765d61d8327deb882cf99','options.clearCache.all=1\noptions.clearCache.pages=1');" | mysql -uroot typo3_test;

# "uninstall" phpunit
  - if [[ -f typo3conf/LocalConfiguration.php ]]; then sed -e "s/,puhpunit//" typo3conf/LocalConfiguration.php | sed -e "s/'phpunit',//" > typo3conf/LocalConfiguration.tmp && cat typo3conf/LocalConfiguration.tmp > typo3conf/LocalConfiguration.php && rm typo3conf/LocalConfiguration.tmp; fi;
  - if [[ -f typo3conf/localconf.php ]]; then sed -e "s/,puhpunit//" typo3conf/localconf.php > typo3conf/localconf.tmp && cat typo3conf/localconf.tmp > typo3conf/localconf.php && rm typo3conf/localconf.tmp; fi;

# Get and install cli_runner
  - git clone --single-branch --recursive --branch master --depth 1 git://github.com/rtp-ch/cli_runner.git typo3conf/ext/cli_runner/;
  - if [[ -f typo3conf/LocalConfiguration.php ]]; then sed -e "s/extbase,/extbase,cli_runner,/" typo3conf/LocalConfiguration.php | sed -e "s/'extbase',/'extbase','cli_runner',/" > typo3conf/LocalConfiguration.tmp && cat typo3conf/LocalConfiguration.tmp > typo3conf/LocalConfiguration.php && rm typo3conf/LocalConfiguration.tmp; fi;
  - if [[ -f typo3conf/localconf.php ]]; then sed -e "s/extbase,/extbase,cli_runner,/" typo3conf/localconf.php > typo3conf/localconf.tmp && cat typo3conf/localconf.tmp > typo3conf/localconf.php && rm typo3conf/localconf.tmp; fi;

# Get and install phpunit
  - git clone --single-branch --recursive --branch master --depth 1 git://git.typo3.org/TYPO3v4/Extensions/phpunit.git typo3conf/ext/phpunit/;
  - php $PWD/typo3/cli_dispatch.phpsh cli_runner --class "RTP\CliRunner\Scripts\Extension" --method install --args phpunit;

# Get and install rtp_imgquery
  - mv rtp_imgquery typo3conf/ext;
  - php $PWD/typo3/cli_dispatch.phpsh cli_runner --class "RTP\CliRunner\Scripts\Extension" --method install --args rtp_imgquery;

script:
  - phpcs --standard=PSR2 --report=summary --ignore=class.ux_tslib_content_image.php,ImageViewHelper.php typo3conf/ext/rtp_imgquery/Classes/
  - phpcs --standard=PSR2 --report=summary typo3conf/ext/rtp_imgquery/Tests/
  #- phpmd typo3conf/ext/rtp_imgquery/Classes/ text codesize,unusedcode,naming
  - php $PWD/typo3/cli_dispatch.phpsh phpunit typo3conf/ext/rtp_imgquery/Tests/
