<?php
return array(
    'Tx_RtpImgQuery_Client_Breakpoints' => 'RTP\RtpImgquery\Client\Breakpoints',
    'Tx_RtpImgQuery_Client_PixelRatios' => 'RTP\RtpImgquery\Client\PixelRatios',
    'Tx_RtpImgQuery_Main_Height' => 'RTP\RtpImgquery\Main\Height',
    'Tx_RtpImgQuery_Main_Image' => 'RTP\RtpImgquery\Main\Image',
    'Tx_RtpImgQuery_Main_Width' => 'RTP\RtpImgquery\Main\Width',
    'Tx_RtpImgQuery_Main_Breakpoint' => 'RTP\RtpImgquery\Main\Breakpoint',
    'Tx_RtpImgQuery_Responsive_Configuration' => 'RTP\RtpImgquery\Responsive\Configuration',
    'Tx_RtpImgQuery_Responsive_Images' => 'RTP\RtpImgquery\Responsive\Images',
    'Tx_RtpImgQuery_Responsive_Strategy' => 'RTP\RtpImgquery\Responsive\Strategy',
    'Tx_RtpImgQuery_Responsive_Style' => 'RTP\RtpImgquery\imgQuery',
    'Tx_RtpImgQuery_imgQuery' => 'RTP\RtpImgquery\Responsive\Style',
    'Tx_RtpImgQuery_Service_Compatibility' => 'RTP\RtpImgquery\Service\Compatibility',
    'Tx_RtpImgQuery_Utility_Html' => 'RTP\RtpImgquery\Utility\Html',
    'Tx_RtpImgQuery_Utility_TypoScript' => 'RTP\RtpImgquery\Utility\TypoScript',
    'Tx_RtpImgQuery_ViewHelpers_ImageViewHelper' => 'RTP\RtpImgquery\ViewHelpers\ImageViewHelper',
    'ux_tslib_content_image' => 'RTP\RtpImgquery\Xclass\ux_tslib_content_image',
    'Tx_RtpImgQuery_Xclass_ImageContentObject' => 'RTP\RtpImgquery\Xclass\ImageContentObject',
);